User belongs to experiment group 'CollectLSRequestTiming - experiment'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
> python3.7 ~/.vscode/extensions/ms-python.python-2021.5.829140558/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 ~/.vscode/extensions/ms-python.python-2021.5.829140558/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 ~/.vscode/extensions/ms-python.python-2021.5.829140558/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 ~/.vscode/extensions/ms-python.python-2021.5.829140558/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.829140558/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python ~/.vscode/extensions/ms-python.python-2021.5.829140558/pythonFiles/pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> conda --version
> pyenv root
> conda info --json
> pyenv root
Python interpreter path: /usr/bin/python3
Error 2021-05-11 07:35:21: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file '/home/joey/Downloads/digit-recognition/.vscode/settings.json' (Error: Unable to resolve non-existing file '/home/joey/Downloads/digit-recognition/.vscode/settings.json')
	at _handleError (/snap/code/63/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:156171)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async y.readText (/home/joey/.vscode/extensions/ms-python.python-2021.5.829140558/out/client/extension.js:9:344717)
	at async p.doesFileNeedToBeFixed (/home/joey/.vscode/extensions/ms-python.python-2021.5.829140558/out/client/extension.js:59:581560)
	at async /home/joey/.vscode/extensions/ms-python.python-2021.5.829140558/out/client/extension.js:59:580687
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (/home/joey/.vscode/extensions/ms-python.python-2021.5.829140558/out/client/extension.js:59:580633)
	at async p.updateTestSettings (/home/joey/.vscode/extensions/ms-python.python-2021.5.829140558/out/client/extension.js:59:580260)] {
  code: 'FileNotFound'
}
Starting Pylance language server.
> pyenv root
> pyenv root
> pyenv root
> conda --version
> pyenv root
> pyenv root
> pyenv root
> pyenv root
> pyenv root
